name: EBAC CI
'on':
  push:
    branches:
      - ci
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.20.2
      - name: Install dependencies
        run: npm i
      - name: Run Tests
        run: |
          npm test
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: ./reports
